# lightning.pytorch==2.5.0.post0
seed_everything: true

trainer:
  enable_checkpointing: false
model:
  input_size: 3319
  learning_rate: 0.0001
data:
  data_folder: ../../data/train_test_cnn/
  batch_size: 32
optimizer: null
lr_scheduler: null
ckpt_path: checkpoints/best-checkpoint-epoch=152-val_loss=1.44.ckpt
verbose: true